services:
  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www/html:rw,z
      - /var/www/html/vendor
      - /var/www/html/node_modules
      - /var/www/html/var
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
      - /home/node/app/.angular
    networks:
      - app-network
    depends_on:
      - backend

  database:
    image: mysql:8.0
    build:
      context: ./database
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    #healthcheck

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: